"""Initial schema with 7 tables

Revision ID: e43725e01c4c
Revises: 
Create Date: 2025-11-07 18:05:48.683472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e43725e01c4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_capacity_hours', sa.Integer(), nullable=False),
    sa.Column('used_capacity_hours', sa.Integer(), nullable=False),
    sa.Column('available_tutors_count', sa.Integer(), nullable=False),
    sa.Column('utilization_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_capacity_subject_date', 'capacity_snapshots', ['subject', 'date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.create_table('data_quality_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('check_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('affected_records_count', sa.Integer(), nullable=True),
    sa.Column('error_details', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_check_status', 'data_quality_log', ['check_name', 'status'], unique=False)
    op.create_index('idx_quality_checked_at', 'data_quality_log', ['checked_at'], unique=False, postgresql_ops={'checked_at': 'DESC'})
    op.create_table('enrollments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('cohort_id', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_enrollments_student', 'enrollments', ['student_id'], unique=False)
    op.create_index('idx_enrollments_subject_date', 'enrollments', ['subject', 'start_date'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('engagement_level', sa.Integer(), nullable=True),
    sa.Column('support_ticket_count', sa.Integer(), nullable=True),
    sa.Column('session_completion_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_health_customer_date', 'health_metrics', ['customer_id', 'date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.create_table('simulation_state',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('current_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speed_multiplier', sa.Integer(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.Column('last_event', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='single_row_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tutor_id', sa.String(length=100), nullable=False),
    sa.Column('subjects', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('weekly_capacity_hours', sa.Integer(), nullable=False),
    sa.Column('utilization_rate', sa.Float(), nullable=True),
    sa.Column('avg_response_time_hours', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tutor_id')
    )
    op.create_index('idx_tutors_subjects', 'tutors', ['subjects'], unique=False, postgresql_using='gin')
    op.create_index('idx_tutors_tutor_id', 'tutors', ['tutor_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('tutor_id', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_sessions_student', 'sessions', ['student_id'], unique=False)
    op.create_index('idx_sessions_subject_time', 'sessions', ['subject', 'scheduled_time'], unique=False)
    op.create_index('idx_sessions_tutor', 'sessions', ['tutor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sessions_tutor', table_name='sessions')
    op.drop_index('idx_sessions_subject_time', table_name='sessions')
    op.drop_index('idx_sessions_student', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_tutors_tutor_id', table_name='tutors')
    op.drop_index('idx_tutors_subjects', table_name='tutors', postgresql_using='gin')
    op.drop_table('tutors')
    op.drop_table('simulation_state')
    op.drop_index('idx_health_customer_date', table_name='health_metrics', postgresql_ops={'date': 'DESC'})
    op.drop_table('health_metrics')
    op.drop_index('idx_enrollments_subject_date', table_name='enrollments')
    op.drop_index('idx_enrollments_student', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('idx_quality_checked_at', table_name='data_quality_log', postgresql_ops={'checked_at': 'DESC'})
    op.drop_index('idx_quality_check_status', table_name='data_quality_log')
    op.drop_table('data_quality_log')
    op.drop_index('idx_capacity_subject_date', table_name='capacity_snapshots', postgresql_ops={'date': 'DESC'})
    op.drop_table('capacity_snapshots')
    # ### end Alembic commands ###
